### ISSUE TITLE
IC14B wrong gain value

### ISSUE THREAD

**Issue by tprzywoz** [sinara-hw/HVSUP_ISOL#10]
R33 15k with R28 10k = 2.5 V/V. We need 5 V/V to reach 0...2.5V.

**Comment by tprzywoz** [comment]
And I think that R79 value should be R33||R28 not R28

**Comment by gkasprow** [comment]
Indeed

**Comment by tprzywoz** [comment]
R33 divided by R28 should be 4, not 3 and as a consequence R79 will be different

**Comment by gkasprow** [comment]
sure, fixed
