### ISSUE TITLE
Oscillations at HVDC converter ctrl pin.

### ISSUE THREAD

**Issue by tprzywoz** [sinara-hw/HVSUP_ISOL#12]
Add capacitor (100 nF) on 5 pin of IC9. There is crosstalk from internal oscillator on ctrl pin. At higher output voltage levels, it is strong enough to keep converter switched on and we lose control.

**Comment by gkasprow** [comment]
it's Royer oscillator base signa. That's why we observe oscillations. Added 100nF capacitor
