### ISSUE TITLE
IC11 PS

### ISSUE THREAD

**Issue by tprzywoz** [sinara-hw/HVSUP_ISOL#13]
IC11 has to be connected to negative power supply, -0.5 V is enough. Without that internal oscillations at CTRL pin of IC9 keep converter switched on even with capacitor #12 (thanks to cap there is option to switch it off by ENABLE signal but no by DAC control signal).

**Comment by gkasprow** [comment]
added -3.3V rail supply, opamps replaced with ADA4510 that can work with >5V
