### ISSUE TITLE
schematic review

### ISSUE THREAD

**Issue by filipswit** [sinara-hw/HVSUP_ISOL#3]
**HV Module**
- [x] Shorted +Vin to -Vin
![image](https://user-images.githubusercontent.com/24258965/161392116-238b9a45-e1b6-44b3-89e5-21e66859199d.png)

- [x] It is recommended to place 1uF **and 100nF** in parallel beside isolation links
- [x] P3V3 shorted with P3V3p through IC27 and IC28 
![image](https://user-images.githubusercontent.com/24258965/161395612-52075f7c-7054-4c20-9ad4-9af1772f9f26.png)

- [x] Missing decap at IC27
- [x] MAX1329: `CAVDD and CDVDD filter capacitor can be a low-ESR tantalum or may need to be a combination of a small ceramic and a larger tantalum capacitor
` It would be probabbly good to change one 10uf ceramic to tantalum

- [x] Missing P3V3 rail

**HVPSU ISOL**

- [x] Useless test point for P3V3A
- [x] Missing ESD strip 
- [x] Separate power connections from CPCIS and EEM parts

**Comment by tprzywoz** [comment]
- [x] MAX1329 RSTs pins are push-pull when configured as interrupt outputs so we need to separate them.

**Comment by filipswit** [comment]
Thanks @tprzywoz, I've added 2 mos keys.
