### ISSUE TITLE
LVDS0 pins swapped

### ISSUE THREAD

**Issue by tprzywoz** [sinara-hw/HVSUP_ISOL#7]
Should be:
D3 -> P
E3 -> N

![image](https://user-images.githubusercontent.com/30114557/236523814-62a6f80c-4891-46ab-828d-60e2ca563a31.png)

**Comment by gkasprow** [comment]
fixed 
![obraz](https://github.com/sinara-hw/HVSUP_ISOL/assets/4325054/265ccf15-6679-499e-9dfc-7fe5d5e23382)
