### ISSUE TITLE
User can not switch PSU OFF

### ISSUE THREAD

**Issue by tprzywoz** [sinara-hw/HVSUP_ISOL#8]
PSU_EN has 1.26 V when LVDS4 is set to low. There is voltage divider between P3V3MP (LED + 220 Ohm) + series 1k resistor R17 at LVDS revceiver output.

**Comment by gkasprow** [comment]
right. We need to add another transistor to drive LED. Temporairly you can swap these 1k and 220R resistors

**Comment by gkasprow** [comment]
added another transistor 
![image](https://github.com/sinara-hw/HVSUP_ISOL/assets/4325054/d8a35d28-0ef0-4931-b39e-e3f2201f6d0b)
