### ISSUE TITLE
Overtemp LED

### ISSUE THREAD

**Issue by tprzywoz** [sinara-hw/HVSUP_ISOL#9]
Even if we fix PSU_EN problem #8, LD7 is on both when the temperature is exceeded and when PSU_EN is turned off manually. We already have PSU_EN led, so LD7 should only indicate overtemp.

**Comment by gkasprow** [comment]
fixed with a dedicated transistor
![image](https://github.com/sinara-hw/HVSUP_ISOL/assets/4325054/a37818a5-e501-4a3d-aa86-269db0e767b8)
